import { FC, useEffect, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { Printer, ArrowLeft } from 'lucide-react'
import { callApi } from '../api/client'
import { formatTime, formatDuration } from '../utils/format'

import { ICall } from '../types/call'

const CallReportPage: FC = () => {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  

  const [data, setData] = useState<ICall | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const fetchReport = async () => {
      try {
        if (!id) return
        const response = await callApi.getById(id)
        setData(response.data as ICall)
      } catch (err) {
        console.error('Failed to fetch call report', err)
      } finally {
        setLoading(false)
      }
    }
    
    fetchReport()
  }, [id])

  if (loading) {
    return <div className="p-8 text-text-muted">Loading report...</div>
  }

  if (!data) {
    return <div className="p-8 text-status-escalated">Report not found.</div>
  }

  return (
    <div className="min-h-screen bg-white">
      {/* ── Screen-only controls (hidden in print) ── */}
      <div className="print:hidden max-w-4xl mx-auto p-4 flex items-center justify-between border-b border-border bg-surface-page rounded-b-2xl mb-8">
        <button 
          onClick={() => navigate('/calls')}
          className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-text-secondary hover:text-text-primary transition-colors"
        >
          <ArrowLeft size={16} /> Back
        </button>
        <button 
          onClick={() => window.print()}
          className="flex items-center gap-2 px-4 py-2 bg-text-primary text-white rounded-lg text-sm font-medium hover:bg-black transition-colors shadow-sm"
        >
          <Printer size={16} /> Print Report
        </button>
      </div>

      {/* ── Printable Area ── */}
      <div className="max-w-4xl mx-auto px-8 pb-12 text-black font-sans">
        
        {/* Header */}
        <div className="border-b-2 border-black pb-6 mb-8 flex items-end justify-between">
          <div>
            <h1 className="text-3xl font-bold tracking-tight mb-2">Call Report</h1>
            <p className="text-sm font-mono text-gray-600">ID: {data.call_id}</p>
          </div>
          <div className="text-right text-sm">
            <p className="font-semibold">{formatTime(data.timestamp).date}</p>
            <p className="text-gray-600">{formatTime(data.timestamp).time}</p>
          </div>
        </div>

        {/* Metadata Grid */}
        <div className="grid grid-cols-2 gap-x-12 gap-y-6 mb-10">
          <div>
            <p className="text-xs font-bold uppercase tracking-widest text-gray-500 mb-1">Caller</p>
            <p className="text-lg font-medium">{data.caller_name ?? 'Unknown'}</p>
            <p className="text-sm font-mono text-gray-700">{data.phone_number}</p>
          </div>
          <div>
            <p className="text-xs font-bold uppercase tracking-widest text-gray-500 mb-1">Status</p>
            <p className="text-lg font-medium capitalize flex items-center gap-2">
              {data.status}
              {(data.is_red_flag || data.is_red_flagged) && <span className="text-xs px-2 py-0.5 border border-red-500 text-red-600 rounded-full font-bold">FLAGGED</span>}
            </p>
          </div>
          <div>
            <p className="text-xs font-bold uppercase tracking-widest text-gray-500 mb-1">Intent</p>
            <p className="text-base">{data.detected_intent ?? '—'}</p>
          </div>
          <div>
            <p className="text-xs font-bold uppercase tracking-widest text-gray-500 mb-1">Duration</p>
            <p className="text-base font-mono">{formatDuration(data.duration)}</p>
          </div>
        </div>

        {/* Summary Section */}
        {data.call_summary && (
          <div className="mb-10">
            <h2 className="text-lg font-bold border-b border-gray-300 pb-2 mb-4">Executive Summary</h2>
            <p className="text-base leading-relaxed text-gray-800">
              {data.call_summary}
            </p>
          </div>
        )}

        {/* Transcript Section */}
        {data.transcript && (
          <div>
            <h2 className="text-lg font-bold border-b border-gray-300 pb-2 mb-4">Full Transcript</h2>
            <div className="bg-gray-50 p-6 rounded-lg border border-gray-200">
              <pre className="text-sm leading-relaxed text-gray-900 whitespace-pre-wrap font-sans">
                {data.transcript}
              </pre>
            </div>
          </div>
        )}
        
        <div className="mt-16 text-center text-xs text-gray-400 print:block hidden">
          Generated by Mantra Tech Agent OS
        </div>
      </div>
    </div>
  )
}

export default CallReportPage
